# Generated by Django 6.0.6 on 2026-06-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.CharField(max_length=11)),
                ('AdiSoyadi', models.CharField(max_length=50)),
                ('Aciklama', models.CharField(max_length=255)),
            ],
        ),
    ]
