#Yaş hesaplama programı
print("*"*5+"Yaş Hesaplama Programına Hoş geldiniz", end="*"*5)
adi=input("\nLütfen size hitap edebilmem için adınızı giriniz.\n")
print("Merhaba", adi)
yas=int(input(f"\n{adi}, hangi yılda doğdunuz?\n"))
print(f"demek {2026-yas} yaşındasınız {adi}.")
kilo=int(input("{} kaç kilosun?\n".format(adi)))
boy=int(input("peki ya boyun kaç {}\n".format (adi)))
ideal_kilo=int(45.5+(boy-152.4)*(2.3/2.54))
fark=int(kilo-ideal_kilo)
print("Biliyormusun {}, aslında senin ideal kilon {} ve\n sen ideal kilondan {} kilo uzaktasın".format (adi, ideal_kilo, fark))